encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:title>", views.get_page, name="get_page"),
    path("search/", views.search, name="search"), 
    path("create_page/", views.create_page, name="create_page"), 
    path("edit/", views.edit, name="edit"), 
    path("random/", views.random, name="random"), 
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls")),
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/forms.py
from django import forms



class Search_Field(forms.Form):
    search_label = forms.CharField(label="" , widget=forms.TextInput(attrs={'placeholder': 'Search Encyclopedia'}))


class NewPageForm(forms.Form):
    pagename = forms.CharField(label="", required = True, 
    widget= forms.Textarea
    (attrs={'placeholder':'Enter Title','value':'TEst','class':'col-lg-4','style':'margin-top:1rem;height:2rem'}))


    content = forms.CharField(label="",required= True,
    widget= forms.Textarea
    (attrs={'placeholder':'Enter markdown content','class':'col-lg-5','style':'top:1rem;height:40%'}))


class EditPage(forms.Form):
    content = forms.CharField(label="",required= True,
    widget= forms.Textarea
    (attrs={'placeholder':'Enter markdown content','class':'col-lg-5','style':'top:1rem;height:40%'}))

encyclopedia/views.py
from re import S
from telnetlib import SE
from django.shortcuts import render
import markdown2
from django.http import HttpResponseRedirect
from django.urls import reverse
from pip import main
import re


from . import util, forms



main_form = forms.Search_Field()



def index(request):
    """
        Return the main index page
    """
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "form" : main_form 
    })


def get_page(request, title):
    """
        1. get the page content from the function
        2. if the page is empty return an error Page
        3. Return a rendererd Page, with the content, markdown = return html code (!!! use safe in template !!!)
    """
    
    page = util.get_entry(title)

    if page is None:
        return render(request, "encyclopedia/error.html", {
            "form" : main_form, 
            "message" : "The requested site was not found, you can create your own"
        })

    else:
        return render(request, "encyclopedia/infopage.html", {
            "title": title,
            "page" : markdown2.markdown(page),
            "form" : main_form 
        })


def search(request):
    """
        1. See if there is Post action happening, else redirect to index page
        2. If yes then geht the search query and get the user to the searched site, else return error page
        3. If search is simmilar to site name, then provied a site with the simmilar results with links to them
    """

    if request.method == "POST":
        form = forms.Search_Field(request.POST)
        if form.is_valid():
            search = util.clean_name(form.cleaned_data["search_label"])
            entries = util.list_entries()
            
            entries_searched = []

            for entry in entries:
                if search.lower() == entry.lower():
                    return get_page(request, search)
                elif search.lower() in entry.lower():
                    entries_searched.append(entry)

            if entries_searched:
                return render(request, "encyclopedia/search.html", {
                    "entries_searched" : entries_searched, 
                    "form" : main_form 
                })
                 
            else:
                return render(request, "encyclopedia/error.html", {
                    "form":form,
                    "message" : "The searched site was not found, you can create your own"
                })

    else:
            return HttpResponseRedirect(reverse("wiki:index"))


def create_page(request):
    """
        1. If request is post = create a new Page else just go to the page to create a new page
        2. get the form Data the Form ( check if valid )
        3. write to a file with the same name as the title and return the new created page

    """


    if request.method == "POST":
        form_data = forms.NewPageForm(request.POST)
        if form_data.is_valid():

            pagename = util.clean_name(form_data.cleaned_data["pagename"])
            content = form_data.cleaned_data["content"]
            

            if pagename.lower() not in [x.lower() for x in util.list_entries()]:
                try:
                    util.save_entry(pagename, content)
                    return get_page(request, pagename)
                except:
                    return render(request, "encyclopedia/error.html", {
                    "form":main_form, 
                    "message" : "Couldn´t save the page, try again"
                    })
            else:
                return render(request, "encyclopedia/error.html", {
                    "form":main_form, 
                    "message" : "Page with that name alredy exists"
                })

            
        else:
            return render(request, "encyclopedia/error.html", {
                "form":main_form
            })
    else:
        return render(request, "encyclopedia/create.html",{
            "form" : main_form,
            "create_form":forms.NewPageForm()
        })


def edit(request):
    """
        1. Two diffrent POST can be done ( one is to get to the edit Page and the other one is tu save the changes)
        2. re was used because we only allow to change the content of the page not the title
        3. again take the input and delete the old file and save a new and return to the new page
        4. if the request is delete, then delete the page from the file
    """

    
    if "edit" in request.POST:
            pagename = request.POST.get("edit")
            page = util.get_entry(pagename)

            try:
                matches = re.search(r"^[#]\s(.*)\n((?:.|\n)*)", page, re.MULTILINE)
                content = matches.group(2).strip()
            except:
                content = ""

            return render(request, "encyclopedia/edit.html", {
                "form": main_form,
                "create_form": forms.EditPage(initial={"content":content}),
                "pagename" : pagename
            })

    elif "save_changes" in request.POST:

            form_data = forms.EditPage(request.POST)
            pagename = request.POST.get("save_changes")

            if form_data.is_valid():

                content = form_data.cleaned_data["content"]
                
                try:
                    util.save_entry(pagename, content)
                except:
                    return render(request, "encyclopedia/error.html", {
                        "form":main_form,
                        "message" : "Couldn´t save the the changes, try again"
                        })

                return render(request, "encyclopedia/infopage.html", {
                    "title": pagename,
                    "page" : markdown2.markdown(util.get_entry(pagename)),
                    "form" : main_form 
                    })

    elif "delete" in request.POST:
        
        pagename = request.POST.get("delete")

        if pagename.lower() in [x.lower() for x in util.list_entries()]:
            
            if not util.delete_page(pagename):
                return render(request, "encyclopedia/error.html", {
                    "form":main_form, 
                    "message" : "Something went wrong, try again"
                })

            return HttpResponseRedirect(reverse("wiki:index"))


def random(request):

    return get_page(request, util.random_page())

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}


{% block title %} Create Page {% endblock %}


{% block body %}
    <h1>Create a new Page</h1>

    <form action="{% url 'wiki:create_page' %}" method="POST">
        {% csrf_token %}
        
        <h3 style="margin-top: 20px">Title:</h3>
        {{ create_form.pagename }}

        <h3 style="margin-top: 20px">Content of Page</h3>
        <p style = "margin-bottom: 0px;">Please use markdwon language</p>
        {{ create_form.content }}

        <input type="submit" class="row" style="margin-top: 50px;margin-left: 17%;" value="Create Page">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}


{% block title %} Edit Page {% endblock %}


{% block body %}
    <h1 style="margin-bottom: 30px;">Edit This Page</h1>
    <h3>Title : {{ pagename }}</h3>
    <form action="{% url 'wiki:edit' %}" method="POST" >
        {% csrf_token %}
        <p style = "margin-bottom: 0px;margin-top: 30px;">Please use markdown language</p>
        {{ create_form.content }}
        <div class="row-10" style="margin-top:5%">
            <button type="submit" class="btn btn-primary" id="save_changes" name ="save_changes" value="{{ pagename }}" style="">Save Changes</button>
            <button type="submit" class="btn btn-danger" id="delete" name ="delete" value="{{ pagename }}" style="">Delete Page</button>
        </div>
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}


{% block title %} Error {% endblock %}


{% block body %}

    <h3>Error Page</h3>
    <p>{{ message }}</p>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>
    <ul>
        {% for entry in entries %}
            <li>
                <a href= "{% url 'wiki:get_page' title=entry %}">{{ entry }}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

encyclopedia/templates/encyclopedia/infopage.html
{% extends "encyclopedia/layout.html" %}


{% block title %} {{ title }} {% endblock %}


{% block body %}
    <form action="{% url 'wiki:edit' %}" method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary"  id="edit" name ="edit" value="{{ title }}" style="margin-left:90%; width: 5%;">edit</button>
        {{ page | safe }}
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:search' %}" method="POST">
                    {% csrf_token %}
                    {{ form }}
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:create_page' %}">Create Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>
    <ul>
        {% for entry in entries_searched %}
            <li>
                <a href= "{% url 'wiki:get_page' title=entry %}">{{ entry }}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}